import { Roboto } from "next/font/google";
import "../globals.css";
import Header from "../components/header";
import AsideMenu from "../components/asideMenu";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="h-screen w-screen md:grid md:grid-rows-[48px_1fr] md:grid-cols-[19vw_auto] bg-[#FBF7F3] text-black">
        <Header />
        <AsideMenu />
        {children}
      </body>
    </html>
  );
}
